// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceDiscovery struct {
	OrderServiceUri      string   `protobuf:"bytes,1,opt,name=order_service_uri,json=orderServiceUri,proto3" json:"order_service_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceDiscovery) Reset()         { *m = ServiceDiscovery{} }
func (m *ServiceDiscovery) String() string { return proto.CompactTextString(m) }
func (*ServiceDiscovery) ProtoMessage()    {}
func (*ServiceDiscovery) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *ServiceDiscovery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDiscovery.Unmarshal(m, b)
}
func (m *ServiceDiscovery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDiscovery.Marshal(b, m, deterministic)
}
func (m *ServiceDiscovery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDiscovery.Merge(m, src)
}
func (m *ServiceDiscovery) XXX_Size() int {
	return xxx_messageInfo_ServiceDiscovery.Size(m)
}
func (m *ServiceDiscovery) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDiscovery.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDiscovery proto.InternalMessageInfo

func (m *ServiceDiscovery) GetOrderServiceUri() string {
	if m != nil {
		return m.OrderServiceUri
	}
	return ""
}

type EventStore struct {
	AggregateId          string   `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateType        string   `protobuf:"bytes,2,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	EventId              string   `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType            string   `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventData            string   `protobuf:"bytes,5,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventStore) Reset()         { *m = EventStore{} }
func (m *EventStore) String() string { return proto.CompactTextString(m) }
func (*EventStore) ProtoMessage()    {}
func (*EventStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *EventStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStore.Unmarshal(m, b)
}
func (m *EventStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStore.Marshal(b, m, deterministic)
}
func (m *EventStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStore.Merge(m, src)
}
func (m *EventStore) XXX_Size() int {
	return xxx_messageInfo_EventStore.Size(m)
}
func (m *EventStore) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStore.DiscardUnknown(m)
}

var xxx_messageInfo_EventStore proto.InternalMessageInfo

func (m *EventStore) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func (m *EventStore) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

func (m *EventStore) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *EventStore) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *EventStore) GetEventData() string {
	if m != nil {
		return m.EventData
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceDiscovery)(nil), "main.ServiceDiscovery")
	proto.RegisterType((*EventStore)(nil), "main.EventStore")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x3f, 0x8f, 0x82, 0x40,
	0x10, 0xc5, 0xc3, 0x1d, 0x77, 0x07, 0x73, 0xff, 0xb7, 0xc2, 0xc2, 0x44, 0x49, 0x4c, 0x8c, 0x85,
	0x8d, 0xbd, 0x15, 0x16, 0xb4, 0xa2, 0x35, 0x59, 0xd8, 0x09, 0xd9, 0x42, 0x76, 0x33, 0xac, 0x24,
	0x7c, 0x2a, 0xbf, 0xa2, 0x61, 0x20, 0x68, 0x39, 0xef, 0xf7, 0x7e, 0x2f, 0x19, 0x08, 0x6c, 0xb1,
	0xb5, 0x64, 0x9c, 0x11, 0xfe, 0x45, 0xea, 0x3a, 0xde, 0xc3, 0x5f, 0x86, 0xd4, 0xea, 0x12, 0x13,
	0xdd, 0x94, 0xa6, 0x45, 0xea, 0xc4, 0x06, 0xfe, 0x0d, 0x29, 0xa4, 0xbc, 0x19, 0x48, 0x7e, 0x25,
	0x1d, 0x79, 0x0b, 0x6f, 0x1d, 0x1e, 0x7f, 0x19, 0x8c, 0xc6, 0x99, 0x74, 0x7c, 0xf3, 0x00, 0x0e,
	0x2d, 0xd6, 0x2e, 0x73, 0x86, 0x50, 0x2c, 0xe1, 0x4b, 0x56, 0x15, 0x61, 0x25, 0x1d, 0xe6, 0x5a,
	0x8d, 0xd6, 0xe7, 0x94, 0xa5, 0x4a, 0xac, 0xe0, 0xe7, 0x51, 0x71, 0x9d, 0xc5, 0xe8, 0x85, 0x4b,
	0xdf, 0x53, 0x7a, 0xea, 0x2c, 0x8a, 0x19, 0x04, 0xd8, 0xef, 0xf6, 0x2b, 0xaf, 0x5c, 0xf8, 0xe0,
	0x3b, 0x55, 0x62, 0x0e, 0x30, 0x20, 0xb6, 0x7d, 0x86, 0x21, 0x27, 0x6c, 0x4e, 0x58, 0x49, 0x27,
	0xa3, 0xb7, 0x27, 0x9c, 0x48, 0x27, 0x8b, 0x77, 0x7e, 0x7f, 0x77, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0xa5, 0x41, 0x1f, 0xf2, 0x0a, 0x01, 0x00, 0x00,
}
